version: "3.3"
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
        - ./Shared:/Code
  redis:
    image: "redis:alpine"
networks:
    default:
        driver: "bridge"
        ipam:
            config:
                - subnet: 172.16.0.0/24